### ISSUE TITLE
Possible to get bimview.s working on mobile

### ISSUE THREAD

**Issue by stonecompass** [opensourceBIM/bimvie.ws#100]
I'm working on getting a solution for showing ifc models on mobile up and running. Is it possible to get bimview.s / BIMSurfer working on a mobile device somehow?

**Comment by stonecompass** [comment]
I didn't set the server up correctly, so I fixed. Sorry! Closing the issue.

**Comment by rubendel** [comment]
It's not, mobile is not supported, pr's are welcome.
