### ISSUE TITLE
How to run bimviews on a standalone machine?

### ISSUE THREAD

**Issue by zyjiang0571** [opensourceBIM/bimvie.ws#104]
I have installed bimserver on a remote server and I need to deploy the bimviews on another web server.  When unzip the  bimviews jar package and deploy it on the web server. Then, accessing  bimviews in Chrome browser, I got lots of errors.  So how to run bimviews on a standalone machine?

**Comment by rubendel** [comment]
Lots of errors, ah then I think I know what the problem is

**Comment by zyjiang0571** [comment]
So, can you solve the problem? thanks!

**Comment by akuckartz** [comment]
@zyjiang0571

> lots of errors

Which errors exactly?
