### ISSUE TITLE
 "Properties" tab has stopped working 

### ISSUE THREAD

**Issue by sigurdne** [opensourceBIM/bimvie.ws#112]
It seems that the "Properties" tab has stopped working for the latest release.
When you click on an element in the model - it used to show the details.
Now - it fails with: 

>Uncaught TypeError: Cannot read property 'x' of null
>    at eval (eval at globalEval (bimviews.js?_v=0.0.109:338), <anonymous>:41:16)
>    at Object.wrapperClass.(:8080/apps/bimviews/anonymous function) [as getMaxBounds] (http://localhost:8080/apps/bimserverjavascriptapi/bimserverapi.umd.js?_v=0.0.147:18180:10)
>    at eval (eval at globalEval (bimviews.js?_v=0.0.109:338), <anonymous>:39:29)
>    at Object.wrapperClass.(:8080/apps/bimviews/anonymous function) [as getMinBounds] (http://localhost:8080/apps/bimserverjavascriptapi/bimserverapi.umd.js?_v=0.0.147:18180:10)
>    at eval (eval at globalEval (bimviews.js?_v=0.0.109:338), <anonymous>:38:28)
>    at Object.wrapperClass.(:8080/apps/bimviews/anonymous function) [as getTransformation] (http://localhost:8080/apps/bimserverjavascriptapi/bimserverapi.umd.js?_v=0.0.147:18196:9)
>    at eval (eval at globalEval (bimviews.js?_v=0.0.109:338), <anonymous>:29:17)
>    at model.js:318
>    at Model.getByX (model.js:550)
>    at Model.get$$1 (model.js:657)

Regards

**Comment by sigurdne** [comment]
I tried the bimserverwar-1.5.109.war from inside a docker container - and here it works fine.
When running the bimserverjar-1.5.109.jar - I got the error.
These are both older than #112
I was not able to run from eclipse to test the latest.

Regards

**Comment by sigurdne** [comment]
My bad.
It was indeed fixed by https://github.com/opensourceBIM/bimvie.ws/commit/24a5debb500b30b5134ada1e42151455689f7d74
The war-version was a new install, and after deleting the home catalog for the jar-version as well, the new version of bimvie.ws was dowloaded on install, and it works.

Regards

**Comment by rubendel** [comment]
Cool, thanks for the update
