### ISSUE TITLE
how to run in Eclipse IDE?

### ISSUE THREAD

**Issue by xierunhua** [opensourceBIM/bimvie.ws#113]

**Comment by xierunhua** [comment]
![image](https://user-images.githubusercontent.com/17872795/46577960-0f0e5b80-ca25-11e8-93bd-c83a2b36c6ad.png)

**Comment by rubendel** [comment]
BIMvie.ws is a HTML/JavaScript application, you need to serve it from a webserver (or from BIMserver).

**Comment by xierunhua** [comment]
one more question !!
how to export the source code to JAR?

**Comment by rubendel** [comment]
Not sure why you would want to do this, but a JAR is just a ZIP file with a different extension, so you can use your favorite zip program.

**Comment by xierunhua** [comment]
Okay. I am interested in BIM online browsing.So I found the BIMServer.
And Naturally, I want to develop the project : bimvie.ws
so I import bimvie.ws into Eclispe IDE. And just try to translate the label name to Chinese.
and then, I have no idea how to run it.
so , just try to export to JAR, and install the pluginbundle.
It is a hard work.

**Comment by rubendel** [comment]
Have you read any of the documentation? For example https://github.com/opensourceBIM/BIMserver/wiki/Eclipse#adding-the-plugins-property
