### ISSUE TITLE
Translation Support

### ISSUE THREAD

**Issue by aaronbach** [opensourceBIM/bimvie.ws#114]
First of all: Thank you for the great Project.

Is there any possibility to translate `bimvie.ws` in other languages, for example german?

Please let me know if there is some `api` or `config`, or if this feature is planned in the future.

Thanks!

**Comment by rubendel** [comment]
This is not planned for the future. BIMvie.ws is just a reference implementation, it's main uses are:
- For developers to test/develop the BIMserver API (I would assume developers to be able to read/write English)
- To serve as an example of what can be done with BIMserver

It's not meant to:
- Be forked and developed further (although there is absolutely no restriction on that other than what's in the license agreement). I personally don't consider the code very extensible, not is it documented.
- Be a frontend for actual users (like Architects etc...)

Hope that makes the intention of this project a bit more clear. Obviously it's open source, so the direction can be changed, but only by contributing actual source code or documentation.

**Comment by rubendel** [comment]
If you are only looking for the 3D viewer part, then you can use [BIMsurfer](https://github.com/opensourceBIM/BIMsurfer), that what BIMvie.ws uses. BIMsurfer (v2) is actually meant to be reused in other projects, more of a component, with an actual (documented) API. I don't know of any other free webbased viewers.

**Comment by aaronbach** [comment]
Thank you!
