### ISSUE TITLE
delete subproject, unable to add it back with the same name

### ISSUE THREAD

**Issue by vipcxj** [opensourceBIM/bimvie.ws#117]
After deleting the subproject, the panel is not refreshed. I must refresh the page myself. but it is just a small problem. The big one is that After I delete the subproject, it seems that it is not really deleted. all the reversions history is left. And I can not add it back with the same name because of the conflict of the name.

**Comment by rubendel** [comment]
There have been numerous issues about this, this is as-designed and it will stay this way for the foreseeable future.
