### ISSUE TITLE
IfcPlugins installation failed

### ISSUE THREAD

**Issue by jkfhto** [opensourceBIM/bimvie.ws#119]
org.bimserver.shared.exceptions.PluginException: Implementation class 'org.bimserver.ifc.step.deserializer.Ifc4StepDeserializerPlugin' not found

![47699318-6e8b1000-dc4d-11e8-85c1-b7b5990a80f9](https://user-images.githubusercontent.com/27767452/47699408-c6c21200-dc4d-11e8-927a-f01bcc723e18.png)

**Comment by rubendel** [comment]
Please read: https://github.com/opensourceBIM/BIMserver/wiki/Plugin-problems

Solution: Just use the latest version of BIMserver.
