### ISSUE TITLE
I need help to solve this error while debugging.

### ISSUE THREAD

**Issue by ikhlassramadan** [opensourceBIM/bimvie.ws#120]
![capture](https://user-images.githubusercontent.com/42959671/47702780-b185bd00-dc26-11e8-97da-bfb62e8083d5.PNG)

**Comment by rubendel** [comment]
Remove your home directory. Databases are not migratable between developer releases.

Next time, put something useful in the title of the issue, this is garbage, also why the hell does this need to be screenshot and not just (searchable) text?

**Comment by rubendel** [comment]
Also closing because this is not about BIMvie.ws
