### ISSUE TITLE
How to install bimvie.ws for BIMserver 1.5?

### ISSUE THREAD

**Issue by siriuszyx** [opensourceBIM/bimvie.ws#121]
Since from 1.5 version you can not just put the .jar into ```\plugins``` directory, what is the right way to do to get it working with BIMserver?

**Comment by aditya84u** [comment]
There is a user exception 503 while installing it as part of BIM Server setup especially on company network.

**Comment by rubendel** [comment]
Unrelevant to original issue, please open a new one, and while you're at it, also include version numbers, log file etc...
