### ISSUE TITLE
Lost texture

### ISSUE THREAD

**Issue by cvc-ru** [opensourceBIM/bimvie.ws#126]
BIMserver 1.5.125
bimviews 0.0.141
Google Chrome 72.0.3626.119 
The first time the object was displayed well.
![image](https://user-images.githubusercontent.com/48197753/53714794-c8e8e700-3e60-11e9-85bf-e652dd0d8b43.png)
Now only surface edges are displayed.
![image](https://user-images.githubusercontent.com/48197753/53714846-fe8dd000-3e60-11e9-8a24-13224385e601.png)
If the eye mark is turned on half, practically nothing is displayed.
![image](https://user-images.githubusercontent.com/48197753/53714893-254c0680-3e61-11e9-95b6-26ee1c7a9b78.png)
What am I doing wrong?

**Comment by rubendel** [comment]
In the 3D view on the top-right, there is an icon you probably clicked on, it switches from triangles to line rendering. Click it again and refresh and it will be back to normal.
