### ISSUE TITLE
Cannot find bimsurfer

### ISSUE THREAD

**Issue by sguionni** [opensourceBIM/bimvie.ws#128]
Hello,
I followed the instructions but i can't launch bimvie.ws :

`
GET http://localhost:8080/apps/bimsurfer/plugin.version 404 (Not Found)
`
(404 for all bimsurfer files)

Am I missing a plugin ? I have BIMSurfer 3 and 2 laucnhed with BIMServer but actually none correspond to the path localhost:8080/apps/bimsurfer

Note that git submodule update seems to be broken because this command is not creating the js/bimsurfer folder (but regarding the errors i don't think this is the main problem).

**Comment by rubendel** [comment]
BIMvie.ws uses BIMsurfer V1

**Comment by sguionni** [comment]
Thanks, had to switch branch (maybe add this to the doc, because v1 and v3 are in the same repo while v2 is in another).
