### ISSUE TITLE
SyntaxError: Unexpected token N in JSON while loading the model in BIMvie.ws

### ISSUE THREAD

**Issue by sameepkaranjkar** [opensourceBIM/bimvie.ws#129]
Operating system : Windows 8
Bimserver version : 1.5.117
Browser : Chrome Version 73.0.3683.103 (Official Build) (64-bit)
The same IFC file worked earlier but when checked in with another project getting same error with both project. While viewing the simple IFC file getting JSON error.

The IFC file used for checkin is as follows : 
[PS_SAMPLE_FILE.txt](https://github.com/opensourceBIM/bimvie.ws/files/3116420/PS_SAMPLE_FILE.txt)

Attached parsed json file where coordinates have NaN :
 {"_t":"Bounds","min":{"_t":"Vector3f","x":**NaN**,"y":**NaN**,"z":**NaN**}
[Parsed_NaN_Json.txt](https://github.com/opensourceBIM/bimvie.ws/files/3116403/Parsed_NaN_Json.txt)

**Error details as follows :** 
bimserverclient.js:571 SyntaxError: Unexpected token N in JSON at position 23009
    at JSON.parse (<anonymous>)
    at XMLHttpRequest.xhr.onload (bimserverclient.js:564)
xhr.onload @ bimserverclient.js:571
model.js:719 Uncaught TypeError: Cannot read property 'forEach' of undefined
    at model.js:719
    at XMLHttpRequest.xhr.onload (bimserverclient.js:574)

Screenshot :
![BIMViews_Error](https://user-images.githubusercontent.com/33112197/56729017-da61b780-675c-11e9-91bd-f284d6a6d08d.JPG)

**Comment by rubendel** [comment]
Pretty sure this is fixed in 1.5.125

**Comment by sameepkaranjkar** [comment]
Upgraded to Bimserver 1.5.125 and seems to be working.Thanks.
