### ISSUE TITLE
How to setup bimvie.ws on BIMserver 1.3 ?

### ISSUE THREAD

**Issue by vpanchal** [opensourceBIM/bimvie.ws#27]
Hi ,

How do I setup bimvie.ws on bimserver1.3 can you please guide me ? I am deploying bimserver1.3 war file in tomcat. Also I tried putting bimvie.ws in plugin folder but I didn't get access.

Please guide me in the same.

**Comment by Siddle111** [comment]
Hi Rubendel,
i have run tomcat in ubuntu system BIMvie.ws modul i can't access browser. when i access it's shows Loading BIMvies... in the header. how can i make it running. please help me.

thank you

**Comment by rubendel** [comment]
I am sorry, but we don't support 1.3, upgrade so a newer version please
