### ISSUE TITLE
Pan (mouse middle button) does not work.

### ISSUE THREAD

**Issue by mcfeely85** [opensourceBIM/bimvie.ws#32]
Hi,

I'm using "bimserver-1.3.2-FINAL-2014-08-21" and "bimviews-1.3.1-FINAL-2014-05-28" on my laptop (Windows 8.1, 64bit). The BIMServer works fine, and the 3D view frame successfully loaded the BIM model and I can use mouse left button to rotate and yaw the model, the select feature works as well. However, I can't get Pan working, the mouse middle button click/drag does nothing to the model, only the browser window moves a bit. I tried IE11 and Chrome. 

Is there a solution for this? 

Thanks

**Comment by vpanchal** [comment]
Solution is implemented in branch only. 
Take latest of PickFlyOrbit.js file it will work.
