### ISSUE TITLE
BimServer Installation

### ISSUE THREAD

**Issue by DavidBenci** [opensourceBIM/bimvie.ws#37]
Hi All,
I am new to BimServer and novice in Linux, I have been asked to install BimServer which I think I have
I am able to get to the admin page and no further, can some help to point me in how to do a install of client and view to be able to add projects as a client and not a s admin

Running Ubuntu 12.04, java 6 and 7 jdk and jre  with tomcat 7
Many thanks David

**Comment by mrca** [comment]
Hello @rubendel I have a similar issue and would therefore not like to open a new issue, but I have completely different settings: 
I have cloned the master repo and am running the project from Eclipse in Windows 7. I have installed the Bimviews plugin and can login normally but then I get the "Loading BIMviews... " window and nothing happens. Could you give me some pointers to what the problem might be? I also dont get anything under localhost:8080/admin address (blank). 

Thanks in advance for the help and sorry for the intrusion in the post.

**Comment by rubendel** [comment]
What's in the javascript console?

**Comment by mrca** [comment]
The connection to ws://localhost:8080/stream was interrupted while the page was loading. admin:1449
GET http://localhost:8080/plugin.version [HTTP/1.1 404 Not Found 3ms]
syntax error plugin.version:1
GET http://localhost:8080/js/bimsurfer/api/SceneJS.js [HTTP/1.1 404 Not Found 20ms]
GET http://localhost:8080/js/bimsurfer/api/Constants.js [HTTP/1.1 404 Not Found 20ms]
GET http://localhost:8080/js/bimsurfer/api/ProgressLoader.js [HTTP/1.1 404 Not Found 17ms]
GET http://localhost:8080/js/bimsurfer/api/Types/Light.js [HTTP/1.1 404 Not Found 17ms]
GET http://localhost:8080/js/bimsurfer/api/Types/Light/Ambient.js [HTTP/1.1 404 Not Found 18ms]
GET http://localhost:8080/js/bimsurfer/api/Types/Light/Sun.js [HTTP/1.1 404 Not Found 19ms]
GET http://localhost:8080/js/bimsurfer/api/Control.js [HTTP/1.1 404 Not Found 21ms]
GET http://localhost:8080/js/bimsurfer/api/Control/ClickSelect.js [HTTP/1.1 404 Not Found 25ms]
GET http://localhost:8080/js/bimsurfer/api/Control/LayerList.js [HTTP/1.1 404 Not Found 19ms]
GET http://localhost:8080/js/bimsurfer/api/Control/ProgressBar.js [HTTP/1.1 404 Not Found 21ms]
GET http://localhost:8080/js/bimsurfer/api/Control/PickFlyOrbit.js [HTTP/1.1 404 Not Found 29ms]
GET http://localhost:8080/js/bimsurfer/api/Control/ObjectTreeView.js [HTTP/1.1 404 Not Found 29ms]
GET http://localhost:8080/js/bimsurfer/api/Events.js [HTTP/1.1 404 Not Found 23ms]
GET http://localhost:8080/js/bimsurfer/api/StringView.js [HTTP/1.1 404 Not Found 26ms]
GET http://localhost:8080/js/bimsurfer/api/GeometryLoader.js [HTTP/1.1 404 Not Found 26ms]
GET http://localhost:8080/js/bimsurfer/api/AsyncStream.js [HTTP/1.1 404 Not Found 27ms]
GET http://localhost:8080/js/bimsurfer/api/DataInputStream.js [HTTP/1.1 404 Not Found 28ms]
GET http://localhost:8080/js/bimsurfer/api/Viewer.js [HTTP/1.1 404 Not Found 27ms]
GET http://localhost:8080/js/bimsurfer/api/Util.js [HTTP/1.1 404 Not Found 28ms]

**Comment by rubendel** [comment]
How did you "install" the BIMvie.ws plugin? Checked-out from github? If so make sure you enable submodules (BIMsurfer is a submodule of BIMvie.ws). Also we are developing in the "1.3" branch of BIMserver, the "master" branch is not used anymore.
