### ISSUE TITLE
bimvie.ws cannot load anything

### ISSUE THREAD

**Issue by reomomoon** [opensourceBIM/bimvie.ws#38]
Hi all,
Two weeks ago,everything is ok when I used bimsie.ws to view ifc models,but now something is wrong. Bimvie.ws just cannot load anything,and the progress bar only shows a half state.and bimsurfer cannot load model either. I take a screen shot as follows,and two weeks ago the version of bimserver was bimserver-1.3.0-FINAL-2014-04-25,the bimsie .ws version was bimviews-1.3.0-FINAL-2014-04-25.Then I tried the newest versions ,which means bimserver-1.3.4-FINAL-2014-10-17 and bimviews-1.3.10-FINAL-2014-12-07,but the results were still the same. the picture follows are the test results of two versions.
Thanks for help 
Mola

![1](https://cloud.githubusercontent.com/assets/7435451/5695141/b8f0a1c2-99cc-11e4-882b-6a61ff2717a2.jpg)
![8](https://cloud.githubusercontent.com/assets/7435451/5695142/c49533da-99cc-11e4-92f5-a7f850c7cd48.jpg)

**Comment by rubendel** [comment]
Newer versions of BIMvie.ws require a newer version of BIMserver. It's impossible to keep al combinations of versions working, so usually the latest version of both will work.
