### ISSUE TITLE
How to make default load of canvas size smaller window size?

### ISSUE THREAD

**Issue by vpanchal** [opensourceBIM/bimvie.ws#39]
Hi,
Currently 3D models loads as per window size or canvas size. How to make default 3D model's size little smaller than the canvas size ?
I have checked code in GeometryLoader.js line no 162 where 3D model loads first time. I want make a change in that. I have also checked code in Viewer.js file in loadScene() method.

Can you guys guide me in the same?

**Comment by rubendel** [comment]
Look at the resize method in 3dview.html
