### ISSUE TITLE
Starting Transaction JSON fails

### ISSUE THREAD

**Issue by EVersluys** [opensourceBIM/bimvie.ws#40]
I have started 8 transaction. Also aborted some.
Now I get this message:

     "__type": "ServerException",
      "message": "Unknown error: org.bimserver.models.store.impl.RevisionImpl cannot be cast to org.bimserver.models.store.Project"

I cannot start any transactions. Is there a flush button?

using BimServer 1.3.4 17-10-2014

**Comment by rubendel** [comment]
Are you sure you are sending a poid and not a roid as the single argument to LowLevelInterface.startTransaction?

**Comment by EVersluys** [comment]
Ruben, your are right, a bit dyslexic. Thnx
