### ISSUE TITLE
not seeing any 3d with bimvie on bimserver 1.4

### ISSUE THREAD

**Issue by johnfoundations** [opensourceBIM/bimvie.ws#45]
hi. i installed bimserver 1.4  which I am running under eclipse and bimvie.ws which I am running under lampp on opensuse 13.1.

I can create a project and check-in a file (architect.ifc) from the samples, and browse it, getting the component information, but 3d view shows nothing.

**Comment by rubendel** [comment]
Anything in your JavaScript console? Which browser? Does WebGL in general work on your browser?

**Comment by johnfoundations** [comment]
It looks like bimsurfer is not installed. I am running opera under apache on opensuse localhost connecting to bimserver launched under eclipse, on port 8080. Opera on linux seems to run webgl ok, as I tried several webgl demo sites that were doing 3d rotating objects and it displayed ok.

Looks like git clone subproject problem to get bimsurfer.

Sorry for slow response. I was having problems where the bimvie was not connecting at all to the bimserver, and then it started to work again .. dont know why.

Good idea to look at javascript console .. i don't know much about debugging javascript

Event thread: load
Uncaught exception: ReferenceError: Undefined variable: BIMSURFER
Error thrown at line 148, column 2 in <anonymous function: show>():
    o.viewer = new BIMSURFER.Viewer(Global.bimServerApi, 'viewport');
called from line 36, column 3 in <anonymous function: showThreeD>():
    threeDView.show();
called via Function.prototype.call() from line 89, column 6 in <anonymous function: changeTab>(response, status, xhr) in http://localhost:81/bimview/js/pagechanger.js?_v=1444140139314:
    callback.call(othis.current);
called via Function.prototype.apply() from unknown location in <anonymous function: each>(a, b, c) in http://localhost:81/bimview/js/jquery-2.1.0.min.js?_v=1444140139314:
    /* no source available */
called from line 2, column 1602 in <anonymous function: each>(a, b) in http://localhost:81/bimview/js/jquery-2.1.0.min.js?_v=1444140139314:
    return o.each(this,a,b)
called from line 4, column 33072 in <anonymous function: o.fn.load>(a, b) in http://localhost:81/bimview/js/jquery-2.1.0.min.js?_v=1444140139314:
    g.each(c,f||[a.responseText,b,a])
called from line 2, column 53204 in <anonymous function: o.Callbacks>(l) in http://localhost:81/bimview/js/jquery-2.1.0.min.js?_v=1444140139314:
    b=a.memory&&l,c=!0,g=e||0,e=0,f=h.length,d=!0
called from line 2, column 54834 in <anonymous function: fireWith>(a, b) in http://localhost:81/bimview/js/jquery-2.1.0.min.js?_v=1444140139314:
    return!h||c&&!i||(b=b||[],b=[a,b.slice?b.slice():b],d?i.push(b):j(b)),this
called from line 4, column 20122 in x(a, b, f, h) in http://localhost:81/bimview/js/jquery-2.1.0.min.js?_v=1444140139314:
    2!==t&&(t=2,g&&clearTimeout(g),c=void 0,e=h||"",v.readyState=a>0?4:0,j=a>=200&&300>a||304===a,f&&(u=uc(k,v,f)),u=vc(k,u,v,j),j?(k.ifModified&&(w=v.getResponseHeader("Last-Modified"),w&&(o.lastModified[d]=w),w=v.getResponseHeader("etag"),w&&(o.etag[d]=w)),204===a||"HEAD"===k.type?x="nocontent":304===a?x="notmodified":(x=u.state,r=u.data,s=u.error,j=!s)):(s=x,(a||!x)&&(x="error",0>a&&(a=0))),v.status=a,v.statusText=(b||x)+"",j?n.resolveWith(l,[r,x,v]):n.rejectWith(l,[v,x,s]),v.statusCode(q),q=void 0,i&&m.trigger(j?"ajaxSuccess":"ajaxError",[v,k,j?r:s]),p.fireWith(l,[v,x]),i&&(m.trigger("ajaxComplete",[v,k]),--o.active||o.event.trigger("ajaxStop")))
called from line 4, column 28101 in <anonymous function: b>() in http://localhost:81/bimview/js/jquery-2.1.0.min.js?_v=1444140139314:
    b&&(delete Dc[g],b=f.onload=f.onerror=null,"abort"===a?f.abort():"error"===a?d(f.status,f.statusText):d(Ec[f.status]||f.status,f.statusText,"string"==typeof f.responseText?{text:f.responseText}:void 0,f.getAllResponseHeaders()))

**Comment by johnfoundations** [comment]
It is working now!! Opera on linux with simple webgl enable (without hardware assist) loaded architect.ifc as a revision and now displays it in 3d.
I still agree with a prior post about being able to set new account password. I really don't want to set up an smtp sender on my development laptop. Easier just to hack the password in the db directly, for testing.

**Comment by johnfoundations** [comment]
Hi Ruben. Things are working quite nicely now. I have built up sub projects.
The project is for civil engineering university students in China. Teach them what BIM means, by showing them various features from BIM server.
At the moment the students basically learn how to use Revit, nothing else, but China wants to adopt BIM .. whatever that means
So we need to translate everything into Chinese, and surround the features with how and why documentation. And the more types of features that we can qualify and explain, the better.
Professors would like collaboration projects, where each student has a sub-project. Figuring out how to add clash detection would be nice.
I am happy enough to have an archive .. and have students check out the IFC and move them into Tekla.
Thanx for your help. I am a Bim server neophyte .. 2 days now .. but could help with testing things.

**Comment by rubendel** [comment]
- The SMTP server is optional, it wil log the email messages in your console when there is no SMTP connection setup, so no need to "hack the db" ;)
- Not sure whether your last comment was supposed to be posted to github
- There has been a problem in Eclipse, where submodules are not loaded automatically (in this case the BimSurfer part of BIMviews), I'll document this on the wiki, thanks for reporting
- Clashdetection has been removed from BIMserver, we expect other projects to jump in and write plugins/remote services
- Would be nice to have Chinese documentation as well, just not sure if it's possible to use the same wiki for it, I'll investigate

**Comment by johnfoundations** [comment]
Hi. My staff will have to do the Chinese, and maybe they can figure out how to contribute it back. Thanx for the console tip.  The warning about BimSurfer maybe not loading is in the documentation. Basically .. bimserver and bimview was plug and play.
I am going to try all of the plug-ins. The one for BCF and Wordpress seems very much like what the universities here are looking for.

**Comment by johnfoundations** [comment]
The Revit plug in for bimserver - it was there in May 2009 .. appears to have disappeared.
The buildingCoder iFC export / import plug in for Revit claims to be loss-less.
If so that old plug in is now very useful.
