### ISSUE TITLE
BIM Surfer installation

### ISSUE THREAD

**Issue by marwessels** [opensourceBIM/bimvie.ws#46]
Hi,
i am running a BIM Server (bimserver-1.4.0-FINAL-2015-09-14) on Apache Tomcat 8.0.26. The Server is running fine and it s possible to connect via  the application opensourceBIM/BIMsurfer (https://github.com/opensourceBIM/BIMsurfer) to the surver and load object. I would like to check another Viewer with Option to see attributes and have some more Option to handle the geometrie.  I try open a Project with https://github.com/halad/MOST_BIMsurfer or https://github.com/paulck/BIMsurferCMDB but i can t connect to the Server. Did anybody have an example to download and run it at Apache?

**Comment by rubendel** [comment]
That does not seem to be an issue related to bimvie.ws. Both projects seem to be not maintained anymore. They probably worked with a BIMserver from 2/3 years ago.
