### ISSUE TITLE
Current Status

### ISSUE THREAD

**Issue by berndhahnebach** [opensourceBIM/bimvie.ws#48]
Hi,
There has been lot of development to bimvie and bimserver recently. I'd like to try them together. What is recommended to use. Is there some stable release or some similar "stable" development version to checkout or download for bimvie and bimserver? 

rind regards bernd

**Comment by rubendel** [comment]
In 1.4, bimviews was delivered with BIMserver, so that combination should work. For 1.5, no plugins (like bimviews) are included in the build, but you can install plugins from maven. 1.5 will probably be released somewhere in the next few months. So for now 1.4 would be your best bet.

**Comment by berndhahnebach** [comment]
Thanks for the fast answer.

Bernd
