### ISSUE TITLE
TypeError: model.queryNew is not a function

### ISSUE THREAD

**Issue by raindog** [opensourceBIM/bimvie.ws#49]
Hi! 
I'm trying to set up bimvie.ws as a client connecting to a bimserver listening on localhost:8082.
The connection is successful but when I try to expand a node on the bimvie.ws tree the following error appears on the console: 

```
TypeError: model.queryNew is not a function. (In 'model.queryNew(preLoadQuery, function(loaded){ })', 'model.queryNew' is undefined)
preloadModel
loadProjectTree
(funzione anonima)
(funzione anonima)tree.js:203
forEach
triggerEventRegistry.js:30
loadtree.js:202
opentree.js:219
toggletree.js:312
(funzione anonima)
dispatchjquery-2.1.3.min.js:2:6449
handlejquery-2.1.3.min.js:2:3224
```

I can reproduce the issue with bimviews-1.3.11-FINAL-2016-01-07 and bimviews-2015-11-04 connecting to a bimserver-1.4.0-FINAL-2015-11-04 on a Mac 10.11.1 with jdk1.8.0_11.

Do you have any hints on how to overcome this thing? Everything else seems to run flawlessly.

**Comment by rubendel** [comment]
This error can definitely happen with a bimviews-1.3.11-FINAL-2016-01-07 combined with bimserver-1.4.0-FINAL-2015-11-04 because they are not compatible. However I can't imagine the BIMvie.ws delivered with bimserver-1.4.0-FINAL-2015-11-04 giving the same error message. Are you sure you tested bimviews-2015-11-04?

**Comment by raindog** [comment]
I WAS sure.
However this morning my brand new bimviews-2015-11-04 copy work as expected.
Maybe I messed up something between the 1.3.11 and 1.4.0 switch.
Thanks Ruben, I hope to be able to return the favour.
