### ISSUE TITLE
Model Compare implementation

### ISSUE THREAD

**Issue by LukeyJohnson** [opensourceBIM/bimvie.ws#50]
I see that User Settings - Model Compares lists two compare engines, including org.bimserver.ifc.compare.GuidBasedModelComparePlugin

How is this currently implemented in bimvie.ws? Is there a method to view or export model compare results at this stage?

**Comment by rubendel** [comment]
Model compare is not implemented in BIMvie.ws. The method would be to use the BIMserver API.
