### ISSUE TITLE
Which version of bimvie.ws corresponds to BIMserver-1.4.0-FINAL-2015-11-04?

### ISSUE THREAD

**Issue by garview** [opensourceBIM/bimvie.ws#51]
i have tried bimvie.ws-1.3.11-FINAL-2016-01-07 and bimviews-1.3.9-FINAL-2014-11-21. 
They are not working properly, and the errors are different.

**Comment by rubendel** [comment]
This question has been answered before, the BIMvie.ws that came with BIMserver 1.4 and BIMserver 1.4, those versions work together.

When you post issues, at least include the error message. The fact that they are different between versions does not give a whole lot of information.

**Comment by garview** [comment]
Please forgive me for my unclear expression.
Now i use the bimvie.ws which is from  BIMserver-1.4.0-FINAL-2015-11-04.jar.  Everything is fine in bimviews page. 
But, open example1.html which  in the bimvie.ws/js/bimsurfer path , and then enter the connection information click on the link. The page is not working properly.
error msg in console:
1. http://127.0.0.1:8080/js/bimserverapi.js?_=1461119828908 Failed to load resource: the server responded with a status of 404 (Not Found)
2. bimserverapibootstrap.js:27 error Could not connect
3. bimserverapibootstrap.js:35 Uncaught TypeError: errorCallback is not a function

Then, I make a copy from BimServer/js/bimserverapi_BimServerApi.js and rename it to bimserverapibootstrap.js, try again.
Of course, it doesn't work.

What should I do to get bimviews/js/bimsurfer/example1.html to work?

**Comment by garview** [comment]
Tested, this example1.html problem exists in multiple versions.
Hope the new version can solve this problem.
