### ISSUE TITLE
add 'rename project'  feature

### ISSUE THREAD

**Issue by berlotti** [opensourceBIM/bimvie.ws#52]
https://github.com/opensourceBIM/BIMserver/issues/330

**Comment by cornhegne** [comment]
need to allow users to rename projects, subprojects, etc... this capability is part of the underlying program, but is not exposed through the user interface.

**Comment by cornhegne** [comment]
Guys is this going to be included in an update?

**Comment by rubendel** [comment]
Added a menu item which will allow you to edit the name, description and merged units. Will be in next release.
