### ISSUE TITLE
Query ThermalTransmittance doesn't work

### ISSUE THREAD

**Issue by Toutoun** [opensourceBIM/bimvie.ws#56]
Hi,
The query "ThermalTransmittance" doesn't work even if the property is present in the original file ifc. 
Why ? Whereas the query "ExternalWalls" works.
Thanks !

**Comment by rubendel** [comment]
Comparing values has not been implemented in the query engine. The "Query" tab is mainly there for testing/demo purposes, probably won't be in the final release.

**Comment by Toutoun** [comment]
Thank you for the info !
How can I implement values in the query engine ? If possible I would.

**Comment by rubendel** [comment]
At this point, I don't think a JSON representation of the query allows for a "clean" way of defining comparisons like ">" etc.

**Comment by rubendel** [comment]
This might be a way to do this, still not very clean though: http://jsonlogic.com/operations.html#numeric-operations
