### ISSUE TITLE
“plugin.version” is not found

### ISSUE THREAD

**Issue by lvxiaomu** [opensourceBIM/bimvie.ws#61]
hi,

I am running bimserverwar-1.5.56.war on a host and running bimviews-0.0.57  on another host with Apache Tomcat 8.5.5.

In settings.js
- getBimServerApiAddress return the location of the BimServerJavaScriptApi installed on a BIMserver
- getBimSurferApiAddress return the location of BIMsurfer installed on a BIMserver.

But when access to the page will be loaded `bimvie.ws-bimviews-0.0.57/plugin.version`
but there is no `plugin.version` in the current directory.

**Comment by rubendel** [comment]
Hi I have updated the other issue with a fourth item: https://github.com/opensourceBIM/bimvie.ws/issues/60
