### ISSUE TITLE
js

### ISSUE THREAD

**Issue by lvxiaomu** [opensourceBIM/bimvie.ws#62]
Hello,
I'm sorry to disturb you,Could you give me a help?
When I visit `http://localhost:8080/bimvie.ws-bimviews-0.0.57/?page=SelectServer`,
 the `?page=SelectServer` loading the content of `<script>` in `index.html` not in `selectserver.html`,so it can't execute `selectServer`. I don't know what's wrong here? 

![image](https://cloud.githubusercontent.com/assets/13172372/18820151/a98ab55a-83cd-11e6-81c5-e449e4c95317.png)

**Comment by lvxiaomu** [comment]
When I visit http://localhost:8080/bimvie.ws-bimviews-0.0.57/?page=SelectServer, 
Is not the code of `<script>` in `index.html` should no longer perform?

**Comment by rubendel** [comment]
Note the question mark (?) in the URL. It should still load index.html (if your webserver is configured to do so, which it probably is). index.html will have a look at the URL parameters and decide what else to load (using "ajax").

**Comment by rubendel** [comment]
A simple "console.log" statement at the the top of the JavaScript in index.html should help you figure out if it's executed.

**Comment by lvxiaomu** [comment]
```
  // https://github.com/rgrove/lazyload
  function l(b) {
    var a = m[b], c, f;
       if (a)
         c = a.callback,
         f = a.urls,
         f.shift(),
         h = 0,
         f.length || (c && c.call(a.context, a.obj),
         m[b] = null ,
         n[b].length && j(b))
  }
```
This `lazyload.js` will execute an error, 
![image](https://cloud.githubusercontent.com/assets/13172372/18824547/737f4778-83f5-11e6-9e75-2ffb46844a6f.png)

**Comment by lvxiaomu** [comment]
Calling `loadBimServerApi()` in the `selectserver.html` as follows

`loadBimServerApi("http://" + address, Global.notifier, Global.version, function(serverInfo){})`

but `loadBimServerApi()` in the `index.html `is defined as follows

`function loadBimServerApi(callback) {}`

Is it a bug of the code?

**Comment by rubendel** [comment]
Ah so you changed the "allowBimServerAddress" settings? It would have been useful if you mentioned that. Do you have multiple BIMservers running? The SelectServer functionality has not been updated to the new BIMserver API. I'll update it a some point.

**Comment by rubendel** [comment]
Just updated it, basically replaced the whole lot with a redirect.

**Comment by lvxiaomu** [comment]
Thank you very much, after the update, already can run!
