### ISSUE TITLE
How does Bimvie.ws work?

### ISSUE THREAD

**Issue by RicoLiu** [opensourceBIM/bimvie.ws#63]
Hi,

Sorry for disturbing you,I have some questions.

How does Bimvie.ws work?
What is a workflow?

![qq 20161010195243](https://cloud.githubusercontent.com/assets/12722992/19235598/3f9b7f68-8f25-11e6-99fe-2f5a42a2ed80.png)

For the above image,
How does 3D model appear?

How to render 3D model?

I have an IFC file and i want to do a demo according to Bimvie.ws
So, 
what should I do?
How should I do?

Looking forward to your reply

**Comment by rubendel** [comment]
I am sorry but I have no clue what you mean to ask. You have gotten as far as showing a 3D model in BIMvie.ws, then you have already seen most the "workflow" I think.

**Comment by RicoLiu** [comment]
oh...I see.I should add a new project and checkin an IFC file.
And 3D model will appear.

Thank you very much
