### ISSUE TITLE
What is difference between Add service and Add service 2?

### ISSUE THREAD

**Issue by RicoLiu** [opensourceBIM/bimvie.ws#64]
Hi,
Sorry for disturbing you.

What is difference between them?
![qq 20161012145135](https://cloud.githubusercontent.com/assets/12722992/19300246/daa0c826-908b-11e6-86e0-10209864ede9.png)

when I click Add service 2,There is an error.
![qq 20161012135415](https://cloud.githubusercontent.com/assets/12722992/19300360/74c78d04-908c-11e6-9fa0-19c651ceed96.png)
Why?

Looking forward to your reply.

**Comment by rubendel** [comment]
That's just some work in progress

**Comment by RicoLiu** [comment]
It means that Add service is same as Add service 2?

**Comment by rubendel** [comment]
No, Add Service 2 will be an alternative way of using services

**Comment by RicoLiu** [comment]
Could you explain them in more detail or give me some tutorials about them?

Thank you very much.
