### ISSUE TITLE
bimvie.ws how to run in IDE , like Eclipse or Intellij

### ISSUE THREAD

**Issue by shiwenna** [opensourceBIM/bimvie.ws#65]
Hi,
I want to break points in the program , but I do not know how to run the program in the IDE . If you can , please let me know.
Thanks.

**Comment by RicoLiu** [comment]
How to debug bimvie.ws in Intellij IDEA?

**Comment by rubendel** [comment]
I use Eclipse, but I don't use the debugging facilities of it when developing BIMvie.ws or any other JavaScript application. Google Chrome has excellent debugging facilities, including stepping through code, inspection, a profiler etc...
