### ISSUE TITLE
Building surrounding environment rendering problem

### ISSUE THREAD

**Issue by shiwenna** [opensourceBIM/bimvie.ws#70]
I have a tree (rendered with Revit) that is imported into bimvie.ws and displayed as follows
![image](https://cloud.githubusercontent.com/assets/13158939/19884124/28a6b00e-a053-11e6-96d8-046105b38954.png)
Is there any way to solve the distortion problem?
Thanks!

**Comment by rubendel** [comment]
Can you share the IFC file?

**Comment by shiwenna** [comment]
Sure!
But the compressed file (zip) failed to upload, you can give me the email address, or other contact information?

**Comment by rubendel** [comment]
Sure, here goes: https://www.dropbox.com/request/bp5C5tZvaWJSE8U5fgvD

**Comment by rubendel** [comment]
Thanks for sharing. When I open the model with Solibri (IFC viewer), the trees look like this as well. So I am pretty sure that the revit IFC export is messing things up here. Maybe you can change export-parameters in Revit, or contact them to fix the export.
