### ISSUE TITLE
Javascript error in Bimvie.ws: expected expression, got keyword 'import'

### ISSUE THREAD

**Issue by stonecompass** [opensourceBIM/bimvie.ws#97]
I have set up a BIMServer v. 1.5.92 and run through the setup.
I can access the Console and create projects and checkin ifc-files easily.
But when it comes to launching bimvie.ws I get the following error message in the browser console:
`expected expression, got keyword 'import'`
The error is at the following line bimviews:113 if that helps.

**Comment by rubendel** [comment]
Which browser are you using?

**Comment by stonecompass** [comment]
I was initially using Chrome. But tried it in the newest version of Firefox and on Safari on a Mac too.

**Comment by marknelissen** [comment]
I confirm the issue in Chrome 62

**Comment by stonecompass** [comment]
I just tried it on another computer where I used Firefox Quantum 57.0 and Chrome Version 62.0.3202.94

**Comment by liqiaolin520** [comment]
我也是，我也是，求帮助

**Comment by stonecompass** [comment]
I just realized that the bimserverjavascriptapi is imported with dynamic import when used in bimview.s, which only works with beta- or dev-versions of Chrome as far as I can tell. I got past the error when using the dev-version, but the object is undefined. Am I doing something wrong or is there a version mismatch?
![screen shot 2017-11-27 at 10 00 31](https://user-images.githubusercontent.com/6901364/33258436-db750d90-d359-11e7-8dec-15ba8720ce8c.png)

**Comment by rubendel** [comment]
I was a bit enthusiastic using the dynamic loading feature, I'll try and come up with a fix that uses static loading (but still uses ES6 modules)

**Comment by stonecompass** [comment]
Okay, well, it's always nice to use great new language features 👍 
Do you have an ETA on when you'll probably have a build with a fix?

**Comment by rubendel** [comment]
Alright that's fixed, when you install a new 1.5.92 version of BIMserver (unchanged release), it will install newer versions of the JS API and BIMvie.ws that will work on Chrome 62.

**Comment by stonecompass** [comment]
Thanks for the quick fix! Sadly I still get a "Loading BIMviews..." and in the Chrome console I get a "Uncaught SyntaxError: Unexpected token import".
I did a fresh install of the BIMServer.
On my Mac I can get BIMvie.ws working on Safari.

**Comment by yiqunc** [comment]
Thanks Ruben! I noticed your changes in BIMviews repo on github, and redownloaded the bimserver war file and did a fresh install, but the same issues are still there (404 - Not Found for apps/bimsurfer/ and showing "Loading BIMviews..." with this error in console:
 
![capture](https://user-images.githubusercontent.com/2689849/33296665-dabc08b8-d430-11e7-9fb3-2b4803dfce9f.JPG)
). 

I am using Google Chrome Version 62.0.3202.94 (Official Build) (64-bit) on Windows 7.  Browser cache is cleaned before reloading. Here is the list of plugin installation logs:

Installing plugins...
		Installing bimsurfer...
		Successfully installed BIMsurfer (org.opensourcebim:bimsurfer:0.0.43)

		Installing bimviews...
		Successfully installed BIMvie.ws (org.opensourcebim:bimviews:0.0.94)

		Installing ifcopenshellplugin...
		Successfully installed IfcOpenShellPlugin (org.opensourcebim:ifcopenshellplugin:0.5.25)

		Installing ifcplugins...
		Successfully installed IfcPlugins (org.opensourcebim:ifcplugins:0.0.33)

		Installing binaryserializers...
		Successfully installed BinarySerializers (org.opensourcebim:binaryserializers:0.0.27)

		Installing bimserverapi...
		Successfully installed BIMServer JavaScript API (org.opensourcebim:bimserverapi:0.0.128)

		Installing console...
		Successfully installed Console (org.opensourcebim:console:0.0.10)

		All remote plugins successfully installed

**Comment by liqiaolin520** [comment]
I put the Google browser to upgrade to the 62 or not

**Comment by liqiaolin520** [comment]
Trouble you to update the, or tell me the latest stable version.
And what's the use of installed bimsurfer, as well as the benefits of the plug-in installed.Thank you for the

**Comment by rubendel** [comment]
Alright, sorry for the hassle. The newest builds of BIMvie.ws and the JavaScript API will work again, it was just a bit too early for using the EcmaScript 6 module system so using a transpiled version for now.

**Comment by pierrejoye** [comment]
For the record here, this error still occurs, I use:
bimserverwar-1.5.92.war
org.opensourcebim.bimviews-0.0.119.jar

It is trying to load:
*:8080/apps/bimserverjavascriptapi/bimserverclient.js
and
*:8080/apps/bimserverjavascriptapi/bimserverapipromise.js

Which is actually:
*:8080/BIMserver/apps/bimserverjavascriptapi/bimserverapipromise.js (with eventually the version)

Also the code could use configuration and co to take care of the paths of the different libraries and co, that would avoid that issue to happen again and make it easier to maintain :)

**Comment by pierrejoye** [comment]
For other having the issue, I am simply putting a proxy in front of BIMserver instance and add rewrite rules for the various version of the bugs as I am not inclined to custom monkey patch each version of it, and easy to add new rules for future similar bugs :)
